import React from 'react'
import Head from 'next/head'
import styles from 'styles/Home.module.css'

import { Header } from 'components/layouts/Header'
import { Footer } from 'components/layouts/Footer'

type Props = {
  children: React.ReactNode
}

const linkItems = [
  { title: 'Top', url: '/' },
  { title: 'Tags', url: '/tags' },
  { title: 'Profile', url: '/profile' },
  { title: 'Contact', url: '/contact' },
]

export const Layout: React.FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Uenishi Web Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-900">
        <header>
          <Header headerItems={linkItems} />
        </header>
        <main className={styles.main}>{children}</main>
        <footer>
          <Footer footerLinks={linkItems} />
        </footer>
      </div>
    </>
  )
}
